AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template untuk VPC di Jakarta (ap-southeast-3)"

Parameters:
  JakartaCIDR:
    Type: String
    Default: "10.0.0.0/16"
    Description: "CIDR block untuk VPC di Jakarta"

Resources:
  JakartaVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref JakartaCIDR
      Tags:
        - Key: Name
          Value: Jakarta-VPC

  JakartaSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref JakartaVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: "ap-southeast-3a"
      Tags:
        - Key: Name
          Value: Jakarta-Subnet

  JakartaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref JakartaVPC
      GroupDescription: "Security group for Jakarta-VPC"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"

  JakartaInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0c1f9d5bae1d8ae80" # AMI ID untuk Jakarta (sesuaikan dengan AMI yang diinginkan)
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref JakartaSubnet
          GroupSet:
            - !Ref JakartaSecurityGroup

Outputs:
  JakartaInstancePublicIP:
    Description: "Public IP dari EC2 instance di Jakarta"
    Value: !GetAtt JakartaInstance.PublicIp

  JakartaVPCID:
    Description: "VPC ID dari Jakarta VPC"
    Value: !Ref JakartaVPC
