AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Template untuk VPC Peering antara Jakarta (ap-southeast-3) dan Singapura (ap-southeast-1)"

Parameters:
  JakartaCIDR:
    Type: String
    Default: "10.0.0.0/16"
    Description: "CIDR block untuk VPC di Jakarta"

  SingaporeCIDR:
    Type: String
    Default: "10.1.0.0/16"
    Description: "CIDR block untuk VPC di Singapura"

Resources:
  JakartaVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref JakartaCIDR
      Tags:
        - Key: Name
          Value: Jakarta-VPC

  SingaporeVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref SingaporeCIDR
      Tags:
        - Key: Name
          Value: Singapore-VPC

  JakartaSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref JakartaVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: "ap-southeast-3a"
      Tags:
        - Key: Name
          Value: Jakarta-Subnet

  SingaporeSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref SingaporeVPC
      CidrBlock: "10.1.1.0/24"
      AvailabilityZone: "ap-southeast-1a"
      Tags:
        - Key: Name
          Value: Singapore-Subnet

  VPCPeeringConnection:
    Type: "AWS::EC2::VPCPeeringConnection"
    Properties:
      VpcId: !Ref JakartaVPC
      PeerVpcId: !Ref SingaporeVPC
      PeerRegion: "ap-southeast-1"

  JakartaRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref JakartaVPC
      Tags:
        - Key: Name
          Value: Jakarta-RouteTable

  SingaporeRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref SingaporeVPC
      Tags:
        - Key: Name
          Value: Singapore-RouteTable

  JakartaRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref JakartaRouteTable
      DestinationCidrBlock: !Ref SingaporeCIDR
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  SingaporeRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref SingaporeRouteTable
      DestinationCidrBlock: !Ref JakartaCIDR
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  JakartaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref JakartaVPC
      GroupDescription: "Security group for Jakarta-VPC"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref SingaporeCIDR

  SingaporeSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref SingaporeVPC
      GroupDescription: "Security group for Singapore-VPC"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Ref JakartaCIDR

  JakartaInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0c1f9d5bae1d8ae80" # AMI ID untuk Jakarta (sesuaikan dengan AMI yang diinginkan)
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref JakartaSubnet
          GroupSet:
            - !Ref JakartaSecurityGroup

  SingaporeInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-01811d4912b4ccb26" # AMI ID untuk Singapura (sesuaikan dengan AMI yang diinginkan)
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref SingaporeSubnet
          GroupSet:
            - !Ref SingaporeSecurityGroup

Outputs:
  JakartaInstancePublicIP:
    Description: "Public IP dari EC2 instance di Jakarta"
    Value: !GetAtt JakartaInstance.PublicIp

  SingaporeInstancePublicIP:
    Description: "Public IP dari EC2 instance di Singapura"
    Value: !GetAtt SingaporeInstance.PublicIp
