AWSTemplateFormatVersion: '2010-09-09'
Description: 'Redis Cluster Deployment within VPC with Authorized Network Access'

Parameters:                                           
  VPC:
    Type: 'AWS::EC2::VPC::Id'
  SubnetA:
    Type: 'AWS::EC2::Subnet::Id'
  SubnetB:
    Type: 'AWS::EC2::Subnet::Id'
  SubnetC:
    Type: 'AWS::EC2::Subnet::Id'
  RedisAuthToken:
    Description: 'Redis AuthToken (password) for securing the Redis cluster'
    Type: String
    NoEcho: true  # Prevents the password from being shown in the CloudFormation console
  AuthorizedNetwork:
    Description: 'First authorized network CIDR block for accessing Redis (e.g., 10.0.0.0/16)'
    Type: String

Resources:
  # Security group for Redis cluster with authorized network access
  CacheSecurityGroup:                                 
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security group for Redis cluster'
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp                               
        FromPort: 6379
        ToPort: 6379
        CidrIp: !Ref AuthorizedNetwork 

  # Subnet group for Redis
  CacheSubnetGroup:                                   
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      Description: 'Subnet group for Redis cluster'
      SubnetIds:
      - Ref: SubnetA                                  
      - Ref: SubnetB
      - Ref: SubnetC

  # Redis cluster
  Cache:
    Type: 'AWS::ElastiCache::ReplicationGroup'
    Properties:
      ReplicationGroupDescription: 'HA Redis Cluster'
      Engine: redis
      CacheNodeType: 'cache.t2.micro'
      NumCacheClusters: 3
      AutomaticFailoverEnabled: true
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      PreferredCacheClusterAZs:
        - ap-southeast-1a
        - ap-southeast-1b
        - ap-southeast-1c
      SecurityGroupIds:
        - !Ref CacheSecurityGroup
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      AuthToken: !Ref RedisAuthToken  # Use the password passed as a parameter
      EngineVersion: 7.1  # Ensure you are using Redis version 6 or above for authentication and encryption support
